### ISSUE TITLE
Update AAAA and A record

### ISSUE THREAD

**Issue by Technikte** [Programie/PHPDynDNS#1]
Some dyndns services with IPv6 and IPv4 support require that both addresses are always included in the update URL. If only the IPv6 address is provided, the A record will be deleted. If only the IPv4 address is provided, the AAAA record will be deleted. 

See https://github.com/opnsense/plugins/issues/1611 in opnsense plugin.
Maybe you could help to add some code to update both ipv4 and ipv6 adress at the same time like `https://dyndns.inwx.com/nic/update?myip=<ipaddr>&myipv6=<ip6addr>` .

**Comment by Programie** [comment]
I guess I found a solution to allow updating both addresses with a single request.

But it will break backward compatibility: The `post_process` option no longer supports the `%ipaddress%` and `%entrytype%` placeholders. Additionally to that, the query parameters for giving the IP addresses are now named `myip` (for specifying the IPv4 address) and `myipv6` (for specifying the IPv6 address), falling back to the client IP address if none was specified.

The change needs a bit more testing, but after that I will create a new release.

**Comment by Programie** [comment]
I've implemented the new feature and released version 3.0.
